'use client';
import {useState,useEffect,useRef,useCallback} from 'react';
import Link from 'next/link';
import {ArrowUpRight,ArrowRight,ArrowDown,Sun,Moon,Menu,Mail,Code2,BriefcaseBusiness,Download,ExternalLink,Pause,Play,BookOpen,ChevronLeft,Database,Layers,AudioLines,ChartNoAxesCombined,BrainCircuit} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {type Content,type Entry,visible,projectsForRole} from '@/lib/content';
import {pageRecord} from '@/lib/page-metadata';
import gsap from 'gsap';
import {browserDatabase} from '@/lib/supabase';
import Aurel from './aurel';
import GitHubActivity from './github-activity';
import {ScrollTrigger} from 'gsap/ScrollTrigger';
import {Flip} from 'gsap/Flip';
gsap.registerPlugin(ScrollTrigger,Flip);
const routes=[['/','Home'],['/projects','Work'],['/about','About'],['/experience','Experience'],['/skills','Skills'],['/achievements','Recognition'],['/certificates','Certificates'],['/resumes','Résumés'],['/contact','Contact']];
export default function Portfolio({initial,initialRevision,path,preview=false}:{initial:Content;initialRevision:number;path:string;preview?:boolean}){
 const [content,setContent]=useState(initial),[revision,setRevision]=useState(initialRevision),[theme,setTheme]=useState(initial.settings.theme),[motion,setMotion]=useState(initial.settings.motion),[menu,setMenu]=useState(false),[filter,setFilter]=useState('all'),[document,setDocument]=useState<Entry|null>(null),[offline,setOffline]=useState(false);
 const root=useRef<HTMLDivElement>(null),grid=useRef<HTMLDivElement>(null),flipState=useRef<any>(null);
 useEffect(()=>{if(!document)return;const updated=[...visible(content,'resumes'),...visible(content,'certificates')].find(x=>x.id===document.id);if(!updated)setDocument(null);else if(!updated.file)setDocument(null);else if(updated.file!==document.file||updated.title!==document.title||updated.subtitle!==document.subtitle)setDocument(updated)},[content,document]);
 const activeRoles=visible(content,'roles');
 useEffect(()=>{if(filter!=='all'&&!activeRoles.some(r=>r.id===filter))setFilter('all')},[content,filter]);
 const p=content.profile,hidden=content.settings.hidden.split(',').map((s:string)=>s.trim()).filter(Boolean);
 useEffect(()=>{if(!preview)window.document.title=pageRecord(content,path).title},[content,path,preview]);
 const navigate=useCallback((href:string)=>{setMenu(false);if(href!==path)window.location.assign(href)},[path]);
 useEffect(()=>{setContent(initial);setRevision(initialRevision)},[initial,initialRevision]);
 useEffect(()=>{const saved=localStorage.getItem('ams-theme');setTheme(saved||content.settings.theme);const savedMotion=localStorage.getItem('ams-motion');setMotion(savedMotion!==null?savedMotion==='true':content.settings.motion&&!matchMedia('(prefers-reduced-motion: reduce)').matches)},[content.settings.theme,content.settings.motion]);
 useEffect(()=>{window.document.documentElement.dataset.theme=theme;window.document.documentElement.dataset.motion=String(motion);window.document.documentElement.dataset.accent=content.settings.accent},[theme,motion,content.settings.accent]);
 useEffect(()=>{if(preview)return;let cancelled=false;let busy=false;const refresh=async()=>{if(busy)return;busy=true;try{const r=await fetch('/api/content',{cache:'no-store'});if(!r.ok)throw Error();const d:any=await r.json();if(!cancelled){if(d.revision!==revision){setContent(d.content);setRevision(d.revision)}setOffline(false)}}catch{if(!cancelled)setOffline(true)}finally{busy=false}};const client=browserDatabase();const source=client.channel('portfolio-published').on('postgres_changes',{event:'*',schema:'public',table:'portfolio_public',filter:'id=eq.main'},()=>void refresh()).subscribe(status=>{if(status==='SUBSCRIBED'){setOffline(false);void refresh()}else if(status==='CHANNEL_ERROR'||status==='TIMED_OUT')setOffline(true)});const reconnect=()=>void refresh();window.addEventListener('online',reconnect);const interval=setInterval(refresh,15000);return()=>{cancelled=true;void client.removeChannel(source);clearInterval(interval);window.removeEventListener('online',reconnect)}},[revision,preview]);
 useEffect(()=>{
  if(!root.current||!motion||matchMedia('(prefers-reduced-motion: reduce)').matches)return;
  const cleanups:Array<()=>void>=[];
  const ctx=gsap.context(()=>{
   gsap.from('.title-word',{yPercent:105,opacity:0,duration:1.05,stagger:.065,ease:'power4.out'});
   gsap.from('.topbar .brand,.topnav a,.top-actions',{y:-10,opacity:0,duration:.65,stagger:.06,ease:'power3.out'});
   gsap.from('.entrance',{y:22,opacity:0,duration:.85,stagger:.11,delay:.18,ease:'power3.out'});
   gsap.utils.toArray<HTMLElement>('.reveal').forEach((el,i)=>{
    gsap.from(el,{y:35,opacity:0,duration:.9,delay:Math.min(i%2*.07,.07),ease:'power3.out',scrollTrigger:{trigger:el,start:'top 94%',once:true}});
   });
   gsap.utils.toArray<HTMLElement>('.skill-group').forEach(el=>gsap.from(el.querySelectorAll('.skill-list span'),{y:14,opacity:0,stagger:.035,duration:.5,ease:'power2.out',scrollTrigger:{trigger:el,start:'top 82%',once:true}}));
   gsap.utils.toArray<HTMLElement>('.experience-row,.recognition-row,.case-body section').forEach(el=>gsap.from(el,{borderColor:'transparent',duration:1.1,scrollTrigger:{trigger:el,start:'top 87%',once:true}}));
   gsap.utils.toArray<HTMLElement>('.section-heading,.footer-top').forEach(el=>gsap.from(el.querySelectorAll('h2, .footer-title, .eyebrow'),{y:18,opacity:0,stagger:.1,duration:.8,scrollTrigger:{trigger:el,start:'top 88%',once:true}}));
   if(root.current?.querySelector('.discipline-strip'))gsap.from('.discipline-link',{opacity:0,y:12,stagger:.08,duration:.6,scrollTrigger:{trigger:'.discipline-strip',start:'top 95%',once:true}});
   if(matchMedia('(min-width: 851px) and (hover: hover) and (pointer: fine)').matches&&root.current?.querySelector('.hero-image'))gsap.to('.hero-image',{yPercent:8,scale:1.05,ease:'none',scrollTrigger:{trigger:'.hero',start:'top top',end:'bottom top',scrub:1}});
   gsap.to('.reading-progress',{scaleX:1,ease:'none',scrollTrigger:{trigger:root.current,start:'top top',end:'bottom bottom',scrub:.3}});
   if(matchMedia('(hover: hover) and (pointer: fine)').matches){
    root.current?.querySelectorAll<HTMLElement>('.project-art').forEach(el=>{
     const move=(e:PointerEvent)=>{const r=el.getBoundingClientRect();gsap.to(el,{rotateX:-(e.clientY-r.top-r.height/2)/r.height*3,rotateY:(e.clientX-r.left-r.width/2)/r.width*3,transformPerspective:1000,duration:.55,ease:'power2.out'})};
     const leave=()=>gsap.to(el,{rotateX:0,rotateY:0,duration:.7,ease:'power3.out'});
     el.addEventListener('pointermove',move);el.addEventListener('pointerleave',leave);cleanups.push(()=>{el.removeEventListener('pointermove',move);el.removeEventListener('pointerleave',leave)});
    });
   }
  },root);
  return()=>{cleanups.forEach(f=>f());ctx.revert()};
 },[path,motion]);

 useEffect(()=>{if(flipState.current&&grid.current&&motion){Flip.from(flipState.current,{duration:.65,ease:'power3.inOut',absolute:true,onEnter:els=>gsap.fromTo(els,{opacity:0,scale:.95},{opacity:1,scale:1,duration:.5})});flipState.current=null}},[filter,motion]);
 useEffect(()=>{if(!motion)return;const frame=requestAnimationFrame(()=>ScrollTrigger.refresh());return()=>cancelAnimationFrame(frame)},[revision,motion]);
 const titleWords=(text:string)=>text.split(/\s+/).map((word,i)=><span className="title-mask" key={i}><span className="title-word">{word}</span>{' '}</span>);
 const chooseFilter=(v:string)=>{if(grid.current&&motion)flipState.current=Flip.getState(grid.current.querySelectorAll('.project-slot'));setFilter(v)};
 const link=(href:string,label:React.ReactNode,cls='')=><Link key={href} href={href} aria-label={cls==='dock-resume'?'View résumés':undefined} className={cls} onClick={e=>{if(e.button!==0||e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;e.preventDefault();navigate(href)}}>{label}</Link>;
 const external=(href:string,label:React.ReactNode,cls='text-link')=>href?<a className={cls} href={href} target="_blank" rel="noopener noreferrer">{label}<ArrowUpRight size={17}/></a>:null;
 const projects=visible(content,'projects');
 const ProjectCard=({item,index}:{item:Entry;index:number})=>{const Icons=[Database,AudioLines,Layers,BrainCircuit,Database,ChartNoAxesCombined];const Icon=Icons[index%Icons.length];return <article className={'project-card reveal tone-'+index%3} data-flip-id={item.id}>
 {link('/projects/'+item.id,<div className="project-art" style={{viewTransitionName:'project-'+item.id} as any}>{item.image?<img src={item.image} alt={item.title} loading="lazy"/>:<><span className="art-index">STUDY / {String(index+1).padStart(2,'0')}</span><Icon className="art-icon" strokeWidth={.6}/><div className="art-title">{item.title==='Consumer360'?<>consumer<span>360</span></>:item.title}</div><span className="art-footer">{item.tags.split(',').slice(0,2).join(' / ')}</span></>}<span className="art-arrow"><ArrowUpRight/></span></div>)}
 <div className="card-meta"><span>{item.subtitle}</span><span>{String(index+1).padStart(2,'0')}</span></div>{link('/projects/'+item.id,<h3>{item.title}</h3>)}<p>{item.description}</p><div className="card-links">{link('/projects/'+item.id,<>Explore case study <ArrowRight size={16}/></>,'text-link')}{external(item.url,<>GitHub</>)}</div></article>};
 const Intro=({number,title,description}:{number:string;title:string;description:string})=><header className="page-intro"><div className="eyebrow entrance">CHAPTER {number} / THE ARCHIVE</div><h1 className="split-title">{titleWords(title)}</h1><p className="entrance">{description}</p></header>;
 const project=path.startsWith('/projects/')?projects.find(x=>x.id===path.split('/')[2]):null;
 const contentPage=()=>{
 if(path!=='/'&&hidden.includes(path.split('/')[1]))return <section className="section route-section"><Intro number="—" title="This chapter is unavailable." description="Explore the other sections of the portfolio."/></section>;
 if(path==='/')return <><section className="hero"><img className="hero-image" src={content.settings.heroImage||'/archive.jpg'} fetchPriority="high" alt="Antique brass armillary sphere in a limestone alcove"/><div className="hero-shade"/><div className="hero-content"><div className="eyebrow entrance"><span className="small-rule"/> DATA · INTELLIGENCE · ENGINEERING</div><h1 className="split-title">{p.headline.split('\n').map((s:string,i:number)=><span key={i} className={i===1?'italic':''}>{titleWords(s)}</span>)}</h1><p className="entrance">{p.introduction}</p><div className="hero-actions entrance">{link('/projects',<>Explore my work <ArrowUpRight size={18}/></>,'button brass')}{link('/resumes',<>View résumés <ArrowRight size={17}/></>,'hero-resume')}</div></div><div className="hero-bottom"><span>{p.location} <span className="sep">/</span> {p.educationSummary.toUpperCase()}</span><a href="#selected">SCROLL TO EXPLORE <ArrowDown size={15}/></a></div><div className="hero-side">THE WORK OF {p.name.toUpperCase()}</div></section>
 {activeRoles.length>0&&<div className="discipline-strip" aria-label="Job profiles">{activeRoles.map((role,i)=>link('/profiles/'+role.id,<><span className="discipline-number">{String(i+1).padStart(2,'0')}</span><span>{role.title}</span><ArrowUpRight size={16}/></>,'discipline-link'))}</div>}
 {!hidden.includes('projects')&&<section id="selected" className="section"><div className="section-heading reveal"><div><div className="eyebrow">01 / SELECTED WORK</div><h2>Built with purpose.<br/><em>Backed by data.</em></h2></div>{link('/projects',<>All projects <ArrowUpRight size={18}/></>,'text-link')}</div><div className="project-grid">{projects.filter(x=>x.featured).map((item,i)=><div className="project-slot" data-flip-id={item.id} key={item.id}>{ProjectCard({item,index:i})}</div>)}</div></section>}
 {!hidden.includes('skills')&&<section className="section home-skills"><div className="section-heading reveal"><div><div className="eyebrow">02 / SKILLS & PRACTICE</div><h2>The tools behind<br/><em>the work.</em></h2></div>{link('/skills',<>Explore my skills <ArrowUpRight size={18}/></>,'text-link')}</div><div className="skill-grid">{visible(content,'skills').map((x,i)=><article key={x.id} className="skill-group reveal"><span className="eyebrow">{String(i+1).padStart(2,'0')} / DISCIPLINE</span><h3>{x.title}</h3><div className="skill-list">{x.description.split(',').filter(t=>t.trim()).map((skill,index)=><span key={index}>{skill.trim()}</span>)}</div></article>)}</div></section>}
 <section className="about-strip section"><div className="eyebrow reveal">03 / THE PERSON BEHIND THE WORK</div><div className="about-quote reveal"><h2>{p.statement.split('\n').map((line:string,i:number)=><span key={i} style={{display:'block'}}>{i===0?line:<em>{line}</em>}</span>)}</h2><p>{p.introduction}</p>{link('/about',<>A little about me <ArrowUpRight size={18}/></>,'text-link')}</div></section>
 {!hidden.includes('experience')&&<section className="section"><div className="section-heading reveal"><div><div className="eyebrow">04 / EXPERIENCE</div><h2>Learning through <em>doing.</em></h2></div>{link('/experience',<>The full journey <ArrowUpRight size={18}/></>,'text-link')}</div>{visible(content,'experience').map((x,i)=><div className="experience-row reveal" key={x.id}><span className="row-index">0{i+1}</span><div><h3>{x.title}</h3><span className="muted">{x.subtitle}</span></div><p>{x.description}</p></div>)}</section>}</>;
 if(path==='/projects'||path.startsWith('/profiles/')){const rolePage=path.startsWith('/profiles/');const selectedRole=rolePage?activeRoles.find(r=>r.id===path.split('/')[2]):activeRoles.find(r=>r.id===filter);const selectedId=rolePage?selectedRole?.id:filter;const shown=selectedId&&selectedId!=='all'?projectsForRole(content,selectedId):projects;return <section className="section route-section">{rolePage&&link('/projects',<><ChevronLeft size={16}/> All work</>,'text-link')}<Intro number="01" title={rolePage?(selectedRole?.title||'Profile unavailable.'):'Selected work.'} description={rolePage?(selectedRole?.description||'This job profile has been removed or unpublished.'):'A collection of questions explored, systems built, and ideas made useful.'}/>{!rolePage&&<div className="filters" aria-label="Filter projects">{[{id:'all',title:'All work'},...activeRoles].map(role=><button key={role.id} aria-pressed={filter===role.id} className={filter===role.id?'active':''} onClick={()=>chooseFilter(role.id)}>{role.title}<sup>{role.id==='all'?projects.length:projectsForRole(content,role.id).length}</sup></button>)}</div>}{(!rolePage||selectedRole)&&<><div className="project-grid" ref={grid}>{shown.map((item,i)=><div className="project-slot" data-flip-id={item.id} key={item.id}>{ProjectCard({item,index:i})}</div>)}</div>{!shown.length&&<div className="collection-empty"><h2>Work in progress.</h2><p>Projects for this profile will appear here when published.</p></div>}</>}</section>}

 if(path.startsWith('/projects/'))return <section className="section route-section">{link('/projects',<><ChevronLeft size={16}/> Back to work</>,'text-link')}{project?<><Intro number="01" title={project.title} description={project.description}/><div className="case-band" style={{viewTransitionName:'project-'+project.id} as any}><span>{project.subtitle}</span><div className="actions">{external(project.url,'View GitHub','button')}{external(project.demo,'Live application','button brass')}</div></div><div className="case-layout"><aside>{(project.roleIds??[]).length>0&&<div className="case-profiles"><div className="eyebrow">JOB PROFILES</div>{activeRoles.filter(r=>(project.roleIds??[]).includes(r.id)).map(role=>link('/profiles/'+role.id,<>{role.title}<ArrowUpRight size={14}/></>,'text-link'))}</div>}<div className="eyebrow">TOOLS & DISCIPLINES</div><div className="tags">{project.tags.split(',').map(t=><span key={t}>{t.trim()}</span>)}</div>{!project.url&&<p className="muted">Repository link will be added when available.</p>}</aside><div className="case-body">{project.image&&<img className="case-image" src={project.image} alt={project.title}/>} {project.details.split('\n\n').map((block,i)=>{const lines=block.split('\n');return <section key={i} className="reveal"><h2>{lines[0]}</h2><p>{lines.slice(1).join('\n')||project.description}</p></section>})}</div></div></>:<Intro number="01" title="This study is unavailable." description="It may have been unpublished or removed. Explore the other projects in the archive."/>}</section>;
 if(path==='/about')return <section className="section route-section"><Intro number="02" title="Always curious." description="The person, the questions, and the work in between."/><div className="about-layout"><div className="portrait reveal">{p.photo?<img src={p.photo} alt={p.name} style={{objectPosition:`50% ${p.photoPosition}%`}}/>:<div className="monogram">A<span>M</span>S<small>ADITYA MOHAN SRIVASTAVA</small></div>}</div><div className="about-body">{p.about.split('\n\n').map((s:string,i:number)=><p key={i} className="reveal">{s}</p>)}{!hidden.includes('education')&&visible(content,'education').map(x=><div className="education reveal" key={x.id}><div className="eyebrow">EDUCATION</div><h3>{x.title}</h3><p>{x.description}</p><span className="muted">{x.subtitle}</span></div>)}</div></div></section>;
 if(path==='/experience')return <section className="section route-section"><Intro number="03" title="Experience, earned." description="Practical work at the intersection of business problems, data, and software."/><div className="timeline">{visible(content,'experience').map((x,i)=><article key={x.id} className="timeline-item reveal"><span className="timeline-number">0{i+1}</span><div><div className="eyebrow">{x.subtitle}</div><h2>{x.title}</h2><p>{x.description}</p>{x.details&&<p>{x.details}</p>}<div className="tags">{x.tags.split(',').filter(Boolean).map(t=><span key={t}>{t}</span>)}</div></div></article>)}</div></section>;
 if(path==='/skills')return <section className="section route-section"><Intro number="04" title="The working toolkit." description="Tools and practices used across my projects, internships, and Consumer360."/><div className="skill-grid">{visible(content,'skills').map((x,i)=><article key={x.id} className="skill-group reveal"><span className="eyebrow">0{i+1} / DISCIPLINE</span><h2>{x.title}</h2><div className="skill-list">{x.description.split(',').map(s=><span key={s}>{s.trim()}</span>)}</div></article>)}</div></section>;
 if(path==='/achievements')return <section className="section route-section"><Intro number="05" title="Beyond the coursework." description="Open-source contributions, shared learning, and a community of builders."/>{visible(content,'achievements').map((x,i)=><article className="recognition-row reveal" key={x.id}><span className="recognition-no">{String(i+1).padStart(2,'0')}</span><div><span className="eyebrow">{x.subtitle}</span><h2>{x.title}</h2><p>{x.description}</p>{external(x.url,'Supporting link')}</div></article>)}</section>;
 if(path==='/certificates'||path==='/resumes'){const resumes=path==='/resumes';return <section className="section route-section"><Intro number={resumes?'07':'06'} title={resumes?'The right perspective.':'Learning, documented.'} description={resumes?'Choose the résumé that best matches the opportunity.':'Certificates and participation across analytics, technology, and AI.'}/><div className="document-grid">{visible(content,resumes?'resumes':'certificates').map((x,i)=><article key={x.id} className="document-card reveal"><div className="document-icon">{x.image?<img src={x.image} alt={x.title}/>:<><BookOpen size={42} strokeWidth={1}/><span>{resumes?'CURRICULUM VITAE':'CREDENTIAL'} / 0{i+1}</span></>}</div><div className="document-body"><span className="eyebrow">{x.subtitle}</span><h2>{x.title}</h2><p>{x.description}</p><div className="actions">{x.file&&<><button className="text-link" onClick={()=>setDocument(x)}>Preview <ExternalLink size={16}/></button><a className="text-link" href={x.file+(x.file.includes('?')?'&':'?')+'download=1'} target="_blank" rel="noopener noreferrer">Download <Download size={16}/></a></>}{external(x.url,'Verify credential')}{!x.file&&!x.url&&<span className="muted">Listed in résumé</span>}</div></div></article>)}</div></section>}
 if(path==='/contact')return <section className="section route-section contact-page"><Intro number="08" title="Let’s build something meaningful." description={activeRoles.length?'For opportunities in '+activeRoles.map(r=>r.title).join(', ')+'.':'Let’s discuss an opportunity or a project.'}/><a href={'mailto:'+p.email} className="contact-email">{p.email}<ArrowUpRight/></a><div className="contact-links">{external('https://mail.google.com/mail/?view=cm&fs=1&to='+encodeURIComponent(p.email),<>Compose in Gmail</>)}{external(p.github,<><Code2 size={19}/> GitHub</>)}{external(p.linkedin,<><BriefcaseBusiness size={19}/> LinkedIn</>)}{link('/resumes',<>View résumés <Download size={17}/></>,'text-link')}</div><p className="muted">Based in {p.location}.</p></section>;
 return <section className="section route-section"><Intro number="—" title="Page not found." description="This chapter is not part of the archive."/>{link('/',<>Return home <ArrowRight/></>,'button')}</section>
 };
 return <div ref={root} className="portfolio"><a className="skip-link" href="#main">Skip to content</a>{preview&&<div className="preview-banner">DRAFT PREVIEW — not visible to visitors</div>}<header className="topbar"><div className="header-inner">{link('/',<><span className="brand-seal" aria-hidden="true">AMS</span><span className="brand-identity"><strong>{p.name}</strong><span>Data, intelligence & engineering</span></span></>,'brand')}<nav className="topnav">{[routes[1],routes[2],routes[4],routes[3],routes[7]].filter(([href])=>!hidden.includes(href.slice(1))).map(([href,label])=>link(href,<span>{content.settings.navigation[href]||label}</span>,path.startsWith(href)?'nav-active':''))}</nav><div className="top-actions"><button aria-label={theme==='dark'?'Switch to light theme':'Switch to dark theme'} className="icon-button" onClick={()=>{const t=theme==='dark'?'light':'dark';setTheme(t);localStorage.setItem('ams-theme',t)}}>{theme==='dark'?<Sun size={19}/>:<Moon size={19}/>}</button>{link('/contact',<>Let’s talk <ArrowUpRight size={16}/></>,'contact-button')}</div></div><div className="reading-progress" aria-hidden="true"/></header><main id="main" key={path}>{contentPage()}{!preview&&path==='/'&&p.github&&<GitHubActivity profile={p.github}/>}</main><footer className="footer"><div className="footer-top"><span className="eyebrow">HAVE A QUESTION OR AN OPPORTUNITY?</span>{link('/contact',<>Let’s connect.<ArrowUpRight/></>,'footer-title')}</div><div className="footer-bottom"><span>© {new Date().getFullYear()} {p.name}</span><div>{external(p.github,'GitHub')}{external(p.linkedin,'LinkedIn')}<a href="/admin">Admin</a></div><span>Made with curiosity.</span></div></footer>{!preview&&<Aurel revision={revision}/>}<div className="floating-dock"><button onClick={()=>setMenu(true)} aria-label="Open navigation menu"><Menu size={18}/><span>Explore</span><span className="dock-cross">+</span></button><span className="dock-divider"/><button className="motion-button" aria-label={motion?'Reduce motion':'Enable animations'} onClick={()=>{setMotion(!motion);localStorage.setItem('ams-motion',String(!motion))}}>{motion?<Pause size={16}/>:<Play size={16}/>}</button><span className="dock-divider"/>{link('/resumes',<Download size={17}/>,'dock-resume')}</div>{offline&&<div className="connection-note" role="status">Reconnecting to live updates…</div>}
 <Dialog open={menu} onOpenChange={setMenu}><DialogContent className="menu-dialog"><DialogTitle className="eyebrow">THE ARCHIVE / INDEX</DialogTitle><DialogDescription className="muted">Explore the work and the story behind it.</DialogDescription><nav>{routes.filter(([href])=>!hidden.includes(href.slice(1))).map(([href,label],i)=><Link href={href} key={href} onClick={e=>{if(e.button!==0||e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;e.preventDefault();navigate(href)}} style={{animationDelay:i*.04+'s'}}><span className="menu-number">{String(i).padStart(2,'0')}</span><span>{content.settings.navigation[href]||label}</span><ArrowUpRight/></Link>)}</nav></DialogContent></Dialog>
 <Dialog open={!!document} onOpenChange={open=>!open&&setDocument(null)}><DialogContent className="pdf-dialog"><DialogTitle>{document?.title}</DialogTitle><DialogDescription>{document?.subtitle}</DialogDescription>{document&&<><iframe title={document.title+' document preview'} src={document.file}/><a className="text-link" href={document.file} target="_blank" rel="noopener noreferrer">Open in a new tab <ExternalLink size={17}/></a><a className="text-link" href={document.file+(document.file.includes('?')?'&':'?')+'download=1'}>Download document <Download size={17}/></a></>}</DialogContent></Dialog></div>
}
