export type Entry = {id:string; title:string; subtitle:string; description:string; details:string; tags:string; url:string; demo:string; file:string; image:string; featured:boolean; published:boolean; order:number; deleted?:boolean; roleIds?:string[]};
export type Content = {profile:{name:string; headline:string; introduction:string; about:string; location:string; email:string; github:string; linkedin:string; photo:string; photoPosition:string; educationSummary:string; statement:string};settings:{theme:string; accent:string; motion:boolean; hidden:string; heroImage:string; navigation:Record<string,string>}; [key:string]:any};
export const categories=['roles','projects','experience','education','skills','achievements','certificates','resumes'];
const entry=(id:string,title:string,subtitle:string,description:string,extra:Partial<Entry>={}):Entry=>({id,title,subtitle,description,details:'',tags:'',url:'',demo:'',file:'',image:'',featured:false,published:true,order:0,...extra});
export const defaultRoles:Entry[]=[
 entry('data-science','Data Science','Models & discovery','Predictive modelling, recommendations, and discovering useful patterns in data.'),
 entry('data-engineering','Data Engineering','Reliable foundations','Data ingestion, transformations, dimensional warehouses, and dependable pipelines.',{order:1}),
 entry('ml-engineering','ML Engineering','Intelligence in applications','Connecting machine learning components to tested applications and useful workflows.',{order:2}),
 entry('data-analytics','Data Analytics','Insight & decisions','Exploratory analysis, dashboards, and clear communication of business findings.',{order:3})
];
export const initialContent:Content={
 profile:{name:'Aditya Mohan Srivastava',headline:'Finding meaning.\nBuilding what matters.',introduction:'I connect data, intelligence, and engineering to turn complex information into useful systems.',about:'I’m Aditya, an Electronics & Communication Engineering undergraduate at JSS Academy of Technical Education, Noida. My work brings together reliable data pipelines, thoughtful analysis, and machine learning.\n\nFrom building PostgreSQL warehouses to exploring music recommendations and consumer intelligence, I enjoy working across the full journey of data: understanding the question, building the system, and making the result useful.\n\nI’m interested in opportunities in Data Science, Data Engineering, ML Engineering, and Data Analytics.',location:'Noida, India',email:'adityamohan132@gmail.com',github:'https://github.com/adityamsr2606',linkedin:'https://www.linkedin.com/in/aditya-mohan-srivastava-ba081a270/',photo:'',photoPosition:'50',educationSummary:'B.Tech · Class of 2027',statement:'Curiosity is the beginning.\nBuilding is how I follow it.'},
 settings:{theme:'dark',accent:'brass',motion:true,hidden:'',heroImage:'/archive.jpg',navigation:{'/':'Home','/projects':'Work','/about':'About','/experience':'Experience','/skills':'Skills','/achievements':'Recognition','/certificates':'Certificates','/resumes':'Résumés','/contact':'Contact'}},
 roles:defaultRoles,
 projects:[
 entry('consumer360','Consumer360','Consumer intelligence platform','A governed data platform connecting ingestion, analytics, topic intelligence, and AI-assisted exploration.',{featured:true,tags:'Data Engineering, Data Science, ML Engineering, Python, PostgreSQL, dbt, Airflow, FastAPI, Sentence Transformers, pytest, Docker',details:'THE PROBLEM\nBring fragmented consumer signals into a traceable analytical foundation.\n\nTHE APPROACH\nYouTube API ingestion feeds layered PostgreSQL schemas. Hash-based deduplication and audit records make ingestion traceable. dbt transformations and Airflow orchestration support analytical workflows.\n\nINTELLIGENCE\nText embeddings, topic clustering, and sentiment analysis provide another lens on audience conversations. FastAPI and guarded natural-language-to-SQL workflows connect the platform to applications.\n\nENGINEERING\nHardening includes API contract tests, provider fallback tests, SQL validation, relation allowlists, and bounded queries.\n\nCURRENT SCOPE\nAn evolving project. The case study describes implemented components; public production deployment and operational scale are not claimed.'}),
 entry('spotify','Spotify Analytics','Patterns behind the playlist','Exploring 99,998 tracks through product analytics, clustering, and personalized recommendations.',{order:1,featured:true,tags:'Data Science, Data Analytics, Python, scikit-learn, Streamlit, Plotly',url:'https://github.com/adityamsr2606/spotify-product-analytics',demo:'https://spotify-interactive-analytic.streamlit.app/',details:'THE QUESTION\nHow can audio features support music discovery and exploratory product analysis?\n\nTHE APPROACH\nA Streamlit application combines feature engineering, K-Means clustering, interactive Plotly charts, cosine similarity, fuzzy search, and preference-based personalization.\n\nDATA\nThe résumé reports a dataset of 99,998 songs. Track attributes support exploratory comparisons and derived engagement measures.\n\nLIMITATIONS\nDerived engagement indicators are proxies. They do not establish observed listening behaviour or causal effects. Recommendation quality needs explicit evaluation beyond visual inspection.'}),
 entry('modern-stack','Modern Data Stack','From records to a warehouse','A dimensional warehouse with modular transformations, quality checks, and analytical reporting.',{order:2,featured:true,tags:'Data Engineering, Data Analytics, Python, PostgreSQL, SSIS, dbt, Power BI',url:'https://github.com/adityamsr2606/modern-data-stack-pipeline',details:'THE PROBLEM\nStandardize business datasets for repeatable analytical queries.\n\nTHE APPROACH\nPython and SSIS ingestion feed PostgreSQL. Thirteen dbt models span staging, intermediate transformations, dimensions, and facts. A star schema supports reporting in Power BI.\n\nREPORTED SCOPE\n300,000+ records across sales, finance, innovation, and product datasets. Documentation and dbt tests support lineage and maintainability.\n\nLIMITATIONS\nA passing test suite establishes that implemented checks passed, not that every possible data defect has been excluded.'}),
 entry('purchase','Purchase Prediction','Understanding conversion','Comparing classification models to predict purchasing from browsing-session features.',{order:3,tags:'Data Science, ML Engineering, Python, scikit-learn, EDA',url:'https://github.com/adityamsr2606/User-Behavior-Based-Purchase-Prediction-Model',details:'THE QUESTION\nCan session-level browsing features help predict purchase intent?\n\nTHE APPROACH\nPreprocessing, feature engineering, and exploratory analysis of the Online Shoppers Intention dataset precede comparison of Logistic Regression, Decision Tree, and Random Forest models.\n\nREPORTED RESULT\n88.97% Random Forest accuracy is reported in the résumé. Features explored include PageValues, BounceRates, and VisitorType.\n\nEVALUATION CONTEXT\nAccuracy should be interpreted alongside the data split, class balance, baseline, and precision/recall. Feature associations should not be read as causal effects.'}),
 entry('turbo','Turbo DataForge','Repeatable ingestion','A configuration-driven pipeline for discovering, standardizing, and loading Excel workbooks.',{order:4,tags:'Data Engineering, Python, PostgreSQL, Pandas, SQLAlchemy, OpenPyXL',url:'https://github.com/adityamsr2606/turbo-dataforge',details:'THE APPROACH\nAutomated workbook discovery, CSV standardization, source-file tracking, and PostgreSQL loading support four enterprise datasets.\n\nENGINEERING FOCUS\nModular configuration separates dataset-specific rules from the shared ingestion workflow. Source tracking supports traceability and repeatable operations.'}),
 entry('retail','Retail EDA Pipeline','From transactions to decisions','Automated cleaning and analysis that turns retail transactions into business reporting.',{order:5,tags:'Data Analytics, Python, Pandas, NumPy, Matplotlib, Excel',url:'https://github.com/adityamsr2606/Retail-EDA-Pipeline',details:'THE APPROACH\nA Python pipeline cleans and validates Excel data containing 499+ retail transactions, then calculates revenue, average order value, category performance, and city-level sales patterns.\n\nOUTPUTS\nCharts, execution logs, and reports in CSV, JSON, and text formats make the analysis reusable.'})],
 experience:[entry('netision','Netision Technology LLP','Data Analyst Intern · Jun – Aug 2026','Built a pipeline processing 800+ records across six Excel workbooks into PostgreSQL. Designed a Landing → Staging → Warehouse architecture and automated validation, normalization, and preprocessing.',{tags:'Python, PostgreSQL, SSIS, SQLAlchemy, Excel'}),entry('ea','EA Technologies USA Inc.','AI Software Development Intern · Aug – Sep 2025','Built AI-enabled business workflows for Tewkesbury Dental Clinic and Elephant Marketing. Contributed multi-source analytics integrations to 1GeniusSEO, including GA4, LinkedIn, and YouTube.',{order:1,tags:'Python, PostgreSQL, REST APIs, Analytics, Workflow automation'})],
 education:[entry('jss','JSS Academy of Technical Education','Noida · Aug 2023 – May 2027','B.Tech in Electronics & Communication Engineering')],
 skills:[entry('eng','Data engineering','01','Python, SQL, PostgreSQL, dbt, Apache Airflow, SSIS, Azure Data Factory, SQLAlchemy, OpenPyXL, Dimensional modelling, API ingestion'),entry('ml','Machine learning & NLP','02','scikit-learn, Sentence Transformers, Text embeddings, Topic clustering, Sentiment analysis, Model evaluation, Feature engineering',{order:1}),entry('analytics','Analytics & visualization','03','Pandas, NumPy, Statistics, EDA, Power BI, Excel, Plotly, Streamlit, Matplotlib, Seaborn',{order:2}),entry('systems','APIs & reliability','04','FastAPI, REST APIs, pytest, Docker, Git, GitHub, SQL validation, Deduplication, Ingestion auditing, API contract testing',{order:3})],
 achievements:[entry('gssoc','GirlScript Summer of Code','2026 · Open source','Ranked among the top 10% of contributors, as reported in my résumé.'),entry('quanta','Quanta Society','Technical team · JSS Noida','Contributing to technical events, engineering initiatives, and collaborative projects.',{order:1}),entry('techbias','Tech Bias','Participation · Quanta Society','Hands-on exposure to electronics, robotics, and collaborative problem solving.',{order:2})],
 certificates:[entry('google','Google Data Analytics','Professional Certificate · Google','Data analysis, data preparation, visualization, and communicating insights.'),entry('guvi','AI Tech Confluence 2025','Participation · HCL GUVI','Participation in AI Tech Confluence 2025.',{order:1})],
 resumes:[entry('resume-ds','Data Science','Résumé · PDF','Machine learning, recommendations, and end-to-end analytical projects.',{file:'/api/media/data-science',tags:'Data Science, ML Engineering'}),entry('resume-de','Data Engineering','Résumé · PDF','Data pipelines, dimensional warehouses, and reliable integration workflows.',{file:'/api/media/data-engineering',tags:'Data Engineering',order:1}),entry('resume-da','Data Analytics','Résumé · PDF','Business analysis, reporting, dashboards, and data preparation.',{file:'/api/media/data-analytics',tags:'Data Analytics',order:2})]
};
export function visible(c:Content,key:string):Entry[]{return (c[key]??[]).filter((x:Entry)=>x.published&&!x.deleted).sort((a:Entry,b:Entry)=>a.order-b.order)}
// Upgrade legacy documents in memory without overwriting published content or drafts.
export function normalizeContent(c:Content):Content{
 const roles:Entry[]=Array.isArray(c.roles)?c.roles:defaultRoles.map(x=>({...x}));
 const out:Content={...c,roles};
 for(const key of ['projects','resumes'])out[key]=(c[key]??[]).map((x:Entry)=>({...x,roleIds:Array.isArray(x.roleIds)?x.roleIds:roles.filter(r=>x.tags.split(',').map(t=>t.trim()).includes(r.title)).map(r=>r.id)}));
 return out;
}
export function publicContent(c:Content):Content{const normalized=normalizeContent(c);const out={...normalized};for(const key of categories)out[key]=visible(normalized,key);const ids=new Set(out.roles.map((r:Entry)=>r.id));for(const key of ['projects','resumes'])out[key]=out[key].map((x:Entry)=>({...x,roleIds:(x.roleIds??[]).filter(id=>ids.has(id))}));return out;}
export function projectsForRole(c:Content,id:string):Entry[]{return visible(c,'projects').filter(x=>(x.roleIds??[]).includes(id))}
